name: test-template.yml
on:
  push:
    branches:
      - main


jobs:
  test-template:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template/vite-react-app
    steps:
      - uses: actions/checkout@v4
        run: |
          pnpm install
          pnpm build
